name: pipeline-scan 

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn clean verify --f pom.xml
      - name: Review artifacts
        run: ls
      - name: Upload war
        uses: actions/upload-artifact@v2
        with:
         name: WebGoatWar
         path: target/webgoat.war
  Upload-and-Scan:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Download war
      uses: actions/download-artifact@v2
      with:
        name: WebGoatWar
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Create folder
      run: mkdir app
    - name: Move artifact
      run: mv webgoat.war app
    - name: Upload and scan
      uses: veracode/veracode-uploadandscan-action@master 
      with: 
        appname: 'WebGoat-2023.4'
        createprofile: 'true'
        filepath: 'app'
        vid: "3848a424a18113931339cf47e3b6203e"
        vkey: "3f808860367da0428092fa323c61981f20c74e5a78a1cf9d33e99be08aeb9b1f788c4119df74d6d6cace3296bf3681286d08fdfc7df91fdb4f6c2db7eb41c174"
        scantimeout: 15
        exclude: '*.js'
        include: '*.war'
        criticality: 'VeryLow'
