name: uploadandscan

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          architecture: x64
      - name: Build with Maven
        run: mvn clean verify --file pom.xml
      - name: Review artifacts
        run: ls target
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
         name: webgoat
         path: target/webgoat-2023.4.jar

  
  Upload-and-Scan:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Download jar
      uses: actions/download-artifact@v3
      with:
        name: webgoat
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Create folder
      run: mkdir app
    - name: Move artifact
      run: mv webgoat-2023.4.jar app
    - name: Upload and scan
      uses: veracode/veracode-uploadandscan-action@master 
      with: 
        appname: 'AlejandraMUBA/WebGoat-A'
        createprofile: 'true'
        filepath: 'app/target/webgoat-2023.4.jar'
        vid: '${{secrets.VERACODE_API_ID}}'
        vkey: '${{secrets.VERACODE_API_KEY}}'
        scantimeout: 15
        exclude: '*.js'
        include: '*.jar'
        criticality: 'VeryHigh'
