name: uploadandscan

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          architecture: x64
      - name: Build with Maven
        run: mvn clean verify --file pom.xml
      - name: Review artifacts
        run: ls target
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
         name: webgoat
         path: target/webgoat-2023.4.jar

  
  Upload-and-Scan:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Download jar
      uses: actions/download-artifact@v3
      with:
        path: webgoat-2023.4.jar
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Create folder
      run: mkdir app
    - name: Verificar folder target
      run: ls target
    - name: Move artifact
      run: mv webgoat-2023.4.jar app
    - name: Verificar folder app
      run: ls app
    - name: Upload and scan
      uses: veracode/veracode-uploadandscan-action@0.2.6 
      with: 
        appname: 'WebGoat-A'
        createprofile: 'true'
        filepath: 'app/webgoat-2023.4.jar'
        vid: "${{secrets.API_ID}}"
        vkey: "${{secrets.API_KEY}}"
        scantimeout: 15
        exclude: '*.js'
        include: '*.jar'
        criticality: 'VeryHigh'
